"""Add body column to BackupStatus

Revision ID: 09453558e4a0
Revises: 
Create Date: 2025-05-19 22:24:24.666358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09453558e4a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backup_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backup_status', schema=None) as batch_op:
        batch_op.drop_column('body')

    # ### end Alembic commands ###
